### ISSUE TITLE
sometimes all mixes are layer 0

### ISSUE THREAD

**Issue by david415** [Katzenpost/server#18]
sometimes all mixes are layer 0

authority 23:14:32.821 DEBU state: Document: &{Epoch:1463 Lambda:0.00025 MaxDelay:46051 Topology:[0]{&{Name:node-5.example.org IdentityKey:9F5E2D5970A8087F81B7BAB8B29B4B8B40EA792B236445523F9F4C3C91A9E431 LinkKey:82619470C2E58B2E4E9C4436506FB697EDFFA416AF955DBA440F0F0B04476B16 MixKeys:map[1463:A2EDFF428CE0D8206F0406D841E6967BC1C8D747402C346A0DCAF68EF597E44E 1464:49EC9C91235D5DD823F497BFF4900BA3B341ABF91F66AB216733C842453EF37C 1465:2F715919693F80A1F1F35CCCEFD264902B2A3DAC504B9F6849BD93BE11BCFF4D] Addresses:[127.0.0.1:30008] Layer:0 LoadWeight:0},&{Name:node-0.example.org IdentityKey:9BC7CE229BE1314393FAB25A9274F745383ED8A5180F15FA0020369C39259593 LinkKey:2D47259711F02181877A8F2B53BC0D1B67095568168B22AC03F4415130EC235D MixKeys:map[1463:788F90C85D77A0FABE74CA21EDAD5602449EF6E53E4B8A2EDEDFA9D8E2891346 1464:AD484D3551296614A7CEA907DE5F7B90EF0BAA71C2892946464EED9FA0985E68 1465:36C53F71CF11387005BA73590127C934F0C294DA158BAAF90D7402652F2B0162] Addresses:[127.0.0.1:30003] Layer:0 LoadWeight:0}},[1]{&{Name:node-2.example.org IdentityKey:29B4585C5EC23F1D13DD8169402FF5DD2D2FA2F270DB6E204FC59668D62210AA LinkKey:55A0D5C73E3301372AD3ECDC72C2E8957DB274A11DBB061006BB500B140EEF01 MixKeys:map[1464:D8C3B313D34A901115D8B7214EC9CFE823BD95CAB1E4586A52943C8774F6DB76 1465:62AF75DC00B1288D207510609B15A73271AED93BB995D1DA5784B7D29AD2557D 1463:F4773AE11A4397AA057DC34930CC0E305BBB4A453A3AD3A7561A9D94C5444C0F] Addresses:[127.0.0.1:30005] Layer:0 LoadWeight:0},&{Name:node-1.example.org IdentityKey:8FB56AE7FFC8B201BD220AAE69C7151EC8D2F9411E35154217E43F78D53A9643 LinkKey:9C77A7031D728C51F81D953C3CB191DF41B18979F565ECFAD72B2F4F1B6F1D5D MixKeys:map[1465:FC64B1CDEC03CFBD0B7E1F004A2D5BF7C48C3B76F15C73044321F8B6749A4C56 1463:3AC29AE162595EB99AB74DC2F14D3EA626C9A3BE3DC0E14DA860A005BB0D8D08 1464:BB18B70F788C3F7493C1DD0E5D846EDA25725EC4574E92875F8DEFA8D0BAB851] Addresses:[127.0.0.1:30004] Layer:0 LoadWeight:0}[2]{&{Name:node-4.example.org IdentityKey:E53CF2771EF9BEFD6595C9E9E6D14A4026DF594B86C12D59E45A22FA284A6737 LinkKey:28FDA95E3261B8015DEE7145AA43529F5BC0ECE423F4A2918729616573F08B29 MixKeys:map[1463:B6F6E1D68CDB6FC115F673C2961D0FA2C1C786C698E4ED2A843B05BEFA9D012F 1464:FF5A7D63EA90EF683044BB59C257E921368E430A2E75C21527F597D384BF2B48 1465:FB5CAF2C1BB766113B5C2D54CBC540FA2F93764FEB7B6AC284FD0EB98097B928] Addresses:[127.0.0.1:30007] Layer:0 LoadWeight:0},&{Name:node-3.example.org IdentityKey:7027FC2D5483D30EFE39CAE0763B7F8ED250B45CCA106E60E1F51A8F2BEFFDA1 LinkKey:C024DFBA601C66F9D5AF8603315D215E7052B4B30269F9E0BD5E777FA0949F3D MixKeys:map[1463:45BEBE2AF2DB9D4DF275B6122A80FCEBE634F672B8917277B757666D30E06C55 1464:A665A84BCE3F62B73B20FFE6E80A07D03EFE04380E71FD72CED426898A08337B 1465:383A7495119ED5A6294C6C7432D85C5F9AF15FD1B9C26D680E9F542A73578B16] Addresses:[127.0.0.1:30006] Layer:0 LoadWeight:0}},}, Providers:[]{&{Name:provider-0.example.org IdentityKey:DB0D582DD2DFE3F0FAFC7A67D37250C54B15985911A8A16051A3F6AFF6B30127 LinkKey:0220DE41C2AC41741D01E989F841A7CC92618C0AC91417BA619C69EFCBC2BF43 MixKeys:map[1463:FCCAA08B904808DFE54245FF614A9AD4880F308B7CA1E227D3FBA6A163B2D744 1464:9562F6A381C7DC65AD5299E5777827B07F7FD659211ED4348C6B1C8CA97EF25E 1465:15CD6388E1F031A9284D89BEECFBB23AFAF4A42AD3293CC0C038B057E4784006] Addresses:[127.0.0.1:30001] Layer:255 LoadWeight:0},&{Name:provider-1.example.org IdentityKey:FC74F0CCB28028D3031E1B673C4280672DDE7F7B06470AC5EA5673A396266C51 LinkKey:83340202E6D04F34C38BD4403FE8A5B03FB02292B75EDA36D3F5EBF2C68C613F MixKeys:map[1463:7EF510E6DB52AC162FB729A4AE4BD526B47656C88B4B58ED3B90BF77A916FC19 1464:5465A46B3854404A0427E3CF74D1490B672135625483F9C3FFC00FADCBE2EE37 1465:5778C891F26D310BCCF1E9790F549BCC88470E93920D6C5AEAA70DEB0C28F942] Addresses:[127.0.0.1:30002] Layer:255 LoadWeight:0}}}

**Comment by Yawning** [comment]
This isn't a bug.
