### ISSUE TITLE
provider crash when receiving message

### ISSUE THREAD

**Issue by david415** [Katzenpost/server#19]
while using our integration test... i was able to send a message through the mixnet only to have it crash when it arrives at the destination provider

provider-1.example.org 00:54:39.268 DEBU incoming:2: RetrieveMessage: 0
panic: BUG: Pool allocated rawPkt has incorrect size

goroutine 263 [running]:
github.com/katzenpost/server.(*packet).copyToRaw(0xc48059e1b0, 0xc4a14d6000, 0xc9dc, 0xc9dc, 0x0, 0x0)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/packet.go:133 +0x11d
github.com/katzenpost/server.(*incomingConn).onSendPacket(0xc480508730, 0xc4a1192600, 0xc480543fb8, 0x3)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:309 +0x57
github.com/katzenpost/server.(*incomingConn).onMixCommand(0xc480508730, 0xa2f440, 0xc4a1192600, 0xc480543e0f)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:233 +0x219
github.com/katzenpost/server.(*incomingConn).worker(0xc480508730)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/incoming_conn.go:218 +0x899
created by github.com/katzenpost/server.(*listener).onNewConn.func1
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/listener.go:93 +0x4f

**Comment by Yawning** [comment]
054e6b2d6cce81882f46a8045a9a6749b20f1e3c should "fix" this, but the static analysis tool will complain (but it's probably ok).
