### ISSUE TITLE
Cannot retreive SURBReply

### ISSUE THREAD

**Issue by david415** [Katzenpost/server#20]
13:22 < dawuud> provider-0.example.org 13:23:00.085 DEBU provider: Stored SURBReply: 11
13:22 < dawuud> provider-0.example.org 13:23:06.635 DEBU incoming:1: RetrieveMessage: 0
13:22 < dawuud> provider-0.example.org 13:23:06.635 DEBU incoming:1: Failed to handle RetreiveMessage: stored SURBReply payload is mis-sized: 51216
13:23 < dawuud> Cannot retreive SURBReply... :(

**Comment by Yawning** [comment]
192d7e8dc62c1485548b72d3c03d9fa6b331d1ab and https://github.com/Katzenpost/core/commit/8b80a2f99bd8e47b48e125757c4b9546d6a6c755
