### ISSUE TITLE
provider: Add the support for loop and discard traffic.

### ISSUE THREAD

**Issue by Yawning** [katzenpost/server#37]
Self explanatory, both are required to implement cover traffic.  The rough outline of how this will be handled is sketched out in https://github.com/katzenpost/docs/blob/master/drafts/kaetzchen.txt though I need to think about certain things some more.

**Comment by Yawning** [comment]
While both of these constructs are only strictly required for mix/provider generated cover traffic, because client cover traffic can be implemented via "send messages to yourself", there isn't anything that keeps clients from using the generic infrastructure, and it's probably better that providers can't clearly pick out cover traffic generated by infrastructure components.

**Comment by Yawning** [comment]
This finished via #39, though I'm still uncertain what the loop case's response payload should be.

**Comment by david415** [comment]
mix loops do not require autoresponder and ideally would not use autoresponders because sphinx routing loops are trivial to create... although for the case of mix loops providers must support the next hop routing command.

**Comment by Yawning** [comment]
Mix loops should use the autoresponder, because otherwise it is possible for a Provider to differentiate between a mix loop and a client loop.

Beyond (obvious) differences at loop packet creation/final arrival and provider processing, there is no functional or behavioral difference between using the autoresponder with a SURB, and just creating a loop packet.
