### ISSUE TITLE
instrument server to expose interesting metrics

### ISSUE THREAD

**Issue by kalikaneko** [katzenpost/server#40]
for research and tuning purposes, we think it might be useful to instrument server to expose some metrics that cannot be obtained on the box: received packet rate, size of the ingress and mixing queue, rate of sphinx drops, etc.

it's been proposed to use prometheus for this; however in order for this to be practical a clean way must be found to allow conditional compilation of the prometheus instrumentation in order not to affect performance.

**Comment by kalikaneko** [comment]
@meskio and myself could work on a first proposal for this if we agree that it's worthy

**Comment by david415** [comment]
optional build tag for building a prometheus metric aggregator via https://github.com/prometheus/client_golang so that the default build would have a no-op function call... yes?

**Comment by moba** [comment]
This part is very important from my perspective, because we want to become a framework for other mixnet research. Tying it specifically to Prometheus does not feel right. On the other hand, I don't know how to expose that data in a more generic way, so maybe this is indeed the way to go.

**Comment by kalikaneko** [comment]
@moba I guess we're talking just about an optional switch that exposes an API from where internal metrics can be agreggated and consumed. This also allows for that data to be consumed to any other tool that's able to parse the results. I would explore how ugly this ends up being, but for a first approach I think it can be very useful.

**Comment by moba** [comment]
We talked this for a bit, and I like it!

**Comment by david415** [comment]
many moons ago meskio submitted this pull request to enable optional build of prometheus agregator:
https://github.com/katzenpost/server/pull/43

after review i shall very likely merge this as i agree it is the correct solution. yawning's silence and refusal to review patches shall no longer block our progress.

**Comment by SuperQ** [comment]
@moba There are many monitoring systems that support reading Prometheus metrics now. Using the Prometheus instrumentation library doesn't mean it only works with Prometheus.

**Comment by david415** [comment]
as of a couple of years ago we have Prometheus integration. certainly it could be improved but the basic metrics are there
