### ISSUE TITLE
add Provider support for Tor onion services

### ISSUE THREAD

**Issue by david415** [katzenpost/server#48]
Providers could listen on a Tor onion service for incoming client connections. To do this we need an onion transport "module". This is a low priority task at this time.

**Comment by Yawning** [comment]
Providers can already publish alternate transport address pairs.  There is no more work to be done here because the provider code should not have special case bullshit for Tor, I2P or anything else beyond "set it up on your own and add stuff to a config file".

**Comment by david415** [comment]
I was thinking that we could use the bulb onion listener code for the Provider onions.
