### ISSUE TITLE
add Parameters() to external kaetzchen plugins

### ISSUE THREAD

**Issue by david415** [katzenpost/server#65]
here in this dev branch i've attempted to modify the grpc and protobuf schema and associated bits of code and golang interface:

https://github.com/katzenpost/server/tree/kaetzchen_plugin_system.0.add_parameters.0

meanwhile here in this other repo i've been trying to get the golang and rust echo services to work with the server:

https://github.com/katzenpost/server_plugins/tree/plugin_parameters.0

however it does NOT work. instead the server hangs on startup. not sure why. maybe it fails to connect to the plugin over the unix domain socket or something?

**Comment by david415** [comment]
I made another attempt and failed in this branch:
https://github.com/katzenpost/server/tree/kaetzchen_plugin_system.0.add_parameters.1

I will come back to this later. Perhaps we need a different methodology for dealing with this go-plugin and grpc system... like perhaps writing a simple test harness would make it more clear what exactly the failure is. Also perhaps we should test grpc schema changes independently from the plugin system.

**Comment by david415** [comment]
22:45 < twim> dawuud: have a look at grpc-gateway
22:45 < twim> it's nice

**Comment by mixmasala** [comment]
I'm not familiar at all with protobufs but I wondered if you need to do something with the context returned from context.Backend(). A look at the unit tests in context_test and example_test suggest that perhaps you should be doing something with the channel returned from ctx.Done(). Thoughts?

**Comment by mixmasala** [comment]
I recreated this issue and noticed that the server_plugin echo-go had the incorrect function declaration, so it's likely you had built echo-go against the wrong branch - I pushed a fix to the server_plugin repo's branch plugin_parameters.0. I tested this using a build against server branch kaetzchen_plugin_system.0.add_parameters.1 and cliclient using the sendKaetzchen command. It looks like it works to me.

**Comment by david415** [comment]
@mixmasala hey actually i used:
* plugin_parameters.0 branch of the server_plugins repo
* reply_bookkeeping.1 branch of the client repo
* kaetzchen_plugin_system.0.add_parameters.1 branch of the server repo
* all other repos on master branches

It does NOT work.
