### ISSUE TITLE
Server's identityKey not initialized

### ISSUE THREAD

**Issue by david415** [Katzenpost/server#7]
while trying to run an integration test i noticed this

https://github.com/Katzenpost/server/tree/mix_implementation.0_add_tests.0
https://github.com/Katzenpost/server/blob/mix_implementation.0_add_tests.0/integration_test.go

'''
go test -v
=== RUN   TestClientServerIntegration
23:00:57.989 NOTI server: Katzenpost is still pre-alpha.  DO NOT DEPEND ON IT FOR STRONG SECURITY OR ANONYMITY.
23:00:57.989 WARN server: Unsafe Debug logging is enabled.
23:00:57.989 NOTI server: Server identifier is: 'katzenpost.example.com'
23:00:57.989 NOTI server: Server identity public key is: 052F2316A2607593C8DC18CB171EC24EBECB1DAB4D3A50617B03879DBE24A8C7
23:00:57.989 NOTI server: Server link public key is: 0C1E8F886A475B06122F921051212DDA14C2ADB6160945290BEA8C6C2D405038
23:00:58.041 NOTI listener:0: Listening on: 127.0.0.1:29483
23:01:03.042 DEBU pki: Halting PKI worker.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x541639]

goroutine 16 [running]:
panic(0x724d80, 0xc420012110)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/katzenpost/core/pki.(*Document).GetMixByKey(0xc420108480, 0xc4200f15e0, 0x20, 0x20, 0x0, 0xc42014cd01, 0xc42016a020)
	/home/user/non-critical/gopath/src/github.com/katzenpost/core/pki/pki.go:91 +0x79
github.com/katzenpost/core/pki.(*Document).GetNodeByKey(0xc420108480, 0xc4200f15e0, 0x20, 0x20, 0xc420180030, 0x70a5e0, 0xc420168060)
	/home/user/non-critical/gopath/src/github.com/katzenpost/core/pki/pki.go:114 +0x4d
github.com/katzenpost/server.newPKICacheEntry(0xc4200ac420, 0xc420108480, 0xc420144140, 0x4df, 0xc420108480)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/pki.go:89 +0x133
github.com/katzenpost/server.(*pki).worker(0xc420102d20)
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/pki.go:217 +0x4ba
created by github.com/katzenpost/server.(*pki).startWorker
	/home/user/non-critical/gopath/src/github.com/katzenpost/server/pki.go:145 +0x5c
exit status 2
FAIL	github.com/katzenpost/server	5.067s
'''

**Comment by Yawning** [comment]
Your test producing broken and fucked up descriptors, is not a server bug.
https://github.com/Katzenpost/server/blob/mix_implementation.0_add_tests.0/integration_test.go#L58

https://github.com/Katzenpost/core/blob/master/pki/pki.go#L129
