### ISSUE TITLE
remove old mix keys

### ISSUE THREAD

**Issue by david415** [katzenpost/server#78]
i noticed the server doesn't delete old mix keys. it should do so.

**Comment by mixmasala** [comment]
I was a bit surprised by this so I took a look. It does appear that keys are written to disk and pruned when the server restarts. I realize this is a trade-off between security and reliability, but at minimum the key material written to disk should be "securely" deleted as soon as the keys are expired. Another option is to persist key material to disk only when the server is gracefully shut down via a signal handler, or not persist key material to disk at all and let clients retransmit.

**Comment by mixmasala** [comment]
also this would be less of an issue with a shorter epoch

**Comment by david415** [comment]
um well the keys are pruned when they expire... but stopping and starting the server at a later time can cause the server to not prune some of the on disk keys.

**Comment by mixmasala** [comment]
keys are pruned from memory when they expire, but I do not think they get pruned from disk until the server is restarted. Some of the on-disk keys won't get pruned even then because they are still valid keys.

**Comment by mixmasala** [comment]
```
root@katzenpost1:~# ls /var/lib/katzenpost/ | grep mixkey | wc -l
381
```

**Comment by david415** [comment]
server/internal/mixkey/mixkey.go has a os.Remove call inside the forceClose method which is called from the Deref method which is called from Prune method in server/mixkeys.go... AND this Prune method is called by publishDescriptorIfNeeded pki method in server/internal/pki/pki.go... this is called from it's worker method.

Therefore the bug must be: "there's a dangling reference"... because it only deletes keys from disk after the ref count goes down to zero. I suspect the ref count doesn't go down to zero due to a bug... something is keeping a reference... or forgets to call Deref.

**Comment by david415** [comment]
nope i was wrong. the real root cause is hilariously complicated and is best explain with my two character patch coming right up...

**Comment by david415** [comment]
https://github.com/katzenpost/server/pull/91
