### ISSUE TITLE
fix data races

### ISSUE THREAD

**Issue by david415** [katzenpost/server#79]
==================
WARNING: DATA RACE
Read at 0x00c4200a8be0 by goroutine 30:
  github.com/katzenpost/server/internal/pki.(*pki).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:196 +0x1478
  github.com/katzenpost/server/internal/pki.(*pki).(github.com/katzenpost/server/internal/pki.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:64 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Previous write at 0x00c4200a8be0 by main goroutine:
  github.com/katzenpost/server.New()
      /home/user/gopath/src/github.com/katzenpost/server/server.go:374 +0x18ac
  main.main()
      /home/user/gopath/src/github.com/katzenpost/daemons/server/main.go:66 +0x40f

Goroutine 30 (running) created at:
  github.com/katzenpost/core/worker.(*Worker).Go()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:36 +0xc4
  github.com/katzenpost/server/internal/pki.(*pki).StartWorker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:64 +0x9e
  github.com/katzenpost/server.New()
      /home/user/gopath/src/github.com/katzenpost/server/server.go:364 +0x15c6
  main.main()
      /home/user/gopath/src/github.com/katzenpost/daemons/server/main.go:66 +0x40f
==================
==================
WARNING: DATA RACE
Read at 0x00c42023a080 by goroutine 55:
  github.com/katzenpost/server.(*serverGlue).Listeners()
      /home/user/gopath/src/github.com/katzenpost/server/server.go:436 +0x54
  github.com/katzenpost/server/internal/pki.(*pki).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:196 +0x1449
  github.com/katzenpost/server/internal/pki.(*pki).(github.com/katzenpost/server/internal/pki.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:64 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Previous write at 0x00c42023a080 by main goroutine:
  github.com/katzenpost/server.New()
      /home/user/gopath/src/github.com/katzenpost/server/server.go:374 +0x18f5
  main.main()
      /home/user/gopath/src/github.com/katzenpost/daemons/server/main.go:66 +0x40f

Goroutine 55 (running) created at:
  github.com/katzenpost/core/worker.(*Worker).Go()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:36 +0xc4
  github.com/katzenpost/server/internal/pki.(*pki).StartWorker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:64 +0x9e
  github.com/katzenpost/server.New()
      /home/user/gopath/src/github.com/katzenpost/server/server.go:364 +0x15c6
  main.main()
      /home/user/gopath/src/github.com/katzenpost/daemons/server/main.go:66 +0x40f
==================
==================
WARNING: DATA RACE
Read at 0x00c42c2e1390 by goroutine 55:
  github.com/katzenpost/server/internal/pki.(*pki).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:196 +0x1478
  github.com/katzenpost/server/internal/pki.(*pki).(github.com/katzenpost/server/internal/pki.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:64 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Previous write at 0x00c42c2e1390 by main goroutine:
  github.com/katzenpost/server.New()
      /home/user/gopath/src/github.com/katzenpost/server/server.go:374 +0x18ac
  main.main()
      /home/user/gopath/src/github.com/katzenpost/daemons/server/main.go:66 +0x40f

Goroutine 55 (running) created at:
  github.com/katzenpost/core/worker.(*Worker).Go()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:36 +0xc4
  github.com/katzenpost/server/internal/pki.(*pki).StartWorker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/pki/pki.go:64 +0x9e
  github.com/katzenpost/server.New()
      /home/user/gopath/src/github.com/katzenpost/server/server.go:364 +0x15c6
  main.main()
      /home/user/gopath/src/github.com/katzenpost/daemons/server/main.go:66 +0x40f
==================

**Comment by david415** [comment]
i just fixed the first race here:
* https://github.com/katzenpost/server/tree/add_tests.0

**Comment by david415** [comment]
==================
WARNING: DATA RACE
Write at 0x00c42c32a270 by goroutine 53:
  github.com/katzenpost/core/wire.(*Session).Close()
      /home/user/gopath/src/github.com/katzenpost/core/wire/session.go:425 +0xc2
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:220 +0x11e5

Previous write at 0x00c42c32a270 by goroutine 54:
  github.com/katzenpost/core/wire.(*Session).RecvCommand()
      /home/user/gopath/src/github.com/katzenpost/core/wire/session.go:371 +0xb2
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker.func2()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:187 +0x98

Goroutine 53 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:104 +0x5c
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:107 +0x12f
  github.com/katzenpost/server/internal/incoming.(*listener).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:91 +0x321
  github.com/katzenpost/server/internal/incoming.(*listener).(github.com/katzenpost/server/internal/incoming.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:171 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Goroutine 54 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:184 +0xae1
==================

**Comment by mixmasala** [comment]
I took a stab at this:
https://github.com/katzenpost/server/tree/datarace_79

**Comment by david415** [comment]
==================
WARNING: DATA RACE
Read at 0x00c4201d1708 by goroutine 48:
  github.com/katzenpost/server/internal/incoming.(*listener).IsConnUnique()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:137 +0x1d0
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:169 +0x8fe

Previous write at 0x00c4201d1708 by goroutine 52:
  [failed to restore the stack]

Goroutine 48 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:104 +0x5c
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:107 +0x12f
  github.com/katzenpost/server/internal/incoming.(*listener).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:91 +0x321
  github.com/katzenpost/server/internal/incoming.(*listener).(github.com/katzenpost/server/internal/incoming.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:171 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Goroutine 52 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:104 +0x5c
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:107 +0x12f
  github.com/katzenpost/server/internal/incoming.(*listener).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:91 +0x321
  github.com/katzenpost/server/internal/incoming.(*listener).(github.com/katzenpost/server/internal/incoming.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:171 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c
==================

**Comment by david415** [comment]
this is the only known reported race after fixing the core/wire race

==================
WARNING: DATA RACE
Read at 0x00c420087228 by goroutine 52:
  github.com/katzenpost/server/internal/incoming.(*listener).IsConnUnique()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:137 +0x1d0
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:169 +0x8fe

Previous write at 0x00c420087228 by goroutine 53:
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:135 +0x287

Goroutine 52 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:104 +0x5c
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:107 +0x12f
  github.com/katzenpost/server/internal/incoming.(*listener).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:91 +0x321
  github.com/katzenpost/server/internal/incoming.(*listener).(github.com/katzenpost/server/internal/incoming.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:171 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c

Goroutine 53 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:104 +0x5c
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:107 +0x12f
  github.com/katzenpost/server/internal/incoming.(*listener).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:91 +0x321
  github.com/katzenpost/server/internal/incoming.(*listener).(github.com/katzenpost/server/internal/incoming.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:171 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c
==================

**Comment by david415** [comment]
fixed in https://github.com/katzenpost/server/pull/83/commits/5244943898861fa664ffdfca4aee9b8f80078905
