### ISSUE TITLE
thwack: Add a way to query statuses of various things.

### ISSUE THREAD

**Issue by Yawning** [katzenpost/server#8]
The management interface should export standardized status for things like connections, resource usage, descriptor download/uploads and etc.

This probably should wait till the server code stabilizes more though.

**Comment by david415** [comment]
meskio suggests adding a command to "list users" on Providers.

also a status commands to list the mix queue size might be useful but ultimately this makes me want a bunch of time series graphs for many metrics.

**Comment by david415** [comment]
thwack works great
