### ISSUE TITLE
incoming conn race condition

### ISSUE THREAD

**Issue by david415** [katzenpost/server#84]
==================
WARNING: DATA RACE
Write at 0x00c4200c00f0 by goroutine 57:
  github.com/katzenpost/core/wire.(*Session).RecvCommand()
      /home/user/gopath/src/github.com/katzenpost/core/wire/session.go:371 +0xb2
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker.func2()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:203 +0x98

Previous read at 0x00c4200c00f0 by goroutine 64:
  github.com/katzenpost/core/wire.(*Session).PeerCredentials()
      /home/user/gopath/src/github.com/katzenpost/core/wire/session.go:431 +0x40
  github.com/katzenpost/server/internal/incoming.(*listener).IsConnUnique()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:147 +0x24a
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:185 +0x944

Goroutine 57 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*incomingConn).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/incoming_conn.go:200 +0xb27

Goroutine 64 (running) created at:
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn.func1()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:109 +0x5c
  github.com/katzenpost/server/internal/incoming.(*listener).onNewConn()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:112 +0x12f
  github.com/katzenpost/server/internal/incoming.(*listener).worker()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:96 +0x321
  github.com/katzenpost/server/internal/incoming.(*listener).(github.com/katzenpost/server/internal/incoming.worker)-fm()
      /home/user/gopath/src/github.com/katzenpost/server/internal/incoming/listener.go:178 +0x41
  github.com/katzenpost/core/worker.(*Worker).Go.func1()
      /home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5c
==================

**Comment by hhalpin** [comment]
This issue was moved to katzenpost/mixnet_uprising#74
